- name: "Configure settings for user '{{ wezterm_user_name }}' in '{{ wezterm_user_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ wezterm_user_config_file_path }}"
    src: "wezterm_lua.j2"
    owner: "{{ wezterm_user_name }}"
  become: true
  become_user: "{{ wezterm_user_name }}"

