- name: "Create wezterm config dir for user '{{ wezterm_user_name }}', if not exist"
  ansible.builtin.file:
    path: "{{ wezterm_user_config_file_path | dirname }}"
    state: directory
  become: true
  become_user: "{{ wezterm_user_name }}"

