- name: "Create wezterm config dir for user '{{ wezterm_user_name }}' at '{{ wezterm_user_config_dir }}'"
  ansible.builtin.file:
    path: "{{ wezterm_user_config_dir }}"
    state: directory
    owner: "{{ wezterm_user_name }}"
    mode: '755'
  become: true
  become_user: root

